spring:
  profiles:
    default: local # for running in local env
    group:
      local: common, local
      prod: common, prod
  application:
    name: cubrainApp
  output:
    ansi:
      enabled: ALWAYS
# ✅ AI 설정 추가

