spring:
  profiles:
    default: local # for running in local env
    group:
      local: common, local
      prod: common, prod
      dev: common, dev
  application:
    name: cubrainApp

  # for logging colors
  output:
    ansi:
      enabled: ALWAYS

  

# for logging
logging:
  level:
    "[org.apache.pdfbox.pdmodel.interactive.annotation.PDAnnotation]": OFF
