spring:
  profiles:
    default: local # for running in local env
    group:
      local: common, local
      prod: common, prod
      dev: common, dev
  application:
    name: cubrainApp
  output:
    ansi:
      enabled: ALWAYS
