spring:
  config:
    activate:
      on-profile: local

  # JPA 설정 (로컬: create로 초기화)
  # hibernate와 flyway schema가 일치하지 않기 때문에 local에서만 사용
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
        ddl-auto: create # 매번 테이블 재생성 (테스트용)
      naming:
        physical-strategy: com.cubrain.springboot_starter_auth.global.logging.CamelCaseToSnakeAndUpperCaseStrategy

  # Flyway 비활성화 (로컬은 ddl-auto 사용)
  flyway:
    enabled: false

  # 소셜 로그인 로직 테스트용(로컬)
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true # static 매핑 활성화 (default true지만 명시)

  # 데이터베이스 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# Swagger 설정 (local에서만 활성화 – Apidog 동기화용)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
